version: "3.8"

services:
  local-db:
    image: mysql:8.0
    container_name: local-db-container
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - db-connect

volumes:
  db-volume:

networks:
  db-connect:
